
// Objective-C API for talking to the following Go packages
//
//	WalletCore/walletcore
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Walletcore_FRAMEWORK_H__
#define __Walletcore_FRAMEWORK_H__

#include "Walletcore.objc.h"
#include "universe.objc.h"

#endif
